apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-05-13T16:30:23Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "14287"
  uid: 149fa850-7481-4cab-9bbd-5acded0ec2f4
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.107.69.19
  clusterIPs:
  - 10.107.69.19
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31599
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
